# Generated by Django 2.2.6 on 2019-10-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JDGoods',
            fields=[
                ('goodid', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('goodsname', models.CharField(max_length=256, verbose_name='商品名')),
                ('goodshop', models.CharField(max_length=128, verbose_name='商铺名')),
                ('goodprice', models.CharField(max_length=128, verbose_name='价格')),
                ('commit_num', models.CharField(max_length=128, verbose_name='评价数')),
                ('goodurl', models.CharField(max_length=256, verbose_name='商品链接')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
            ],
        ),
        migrations.CreateModel(
            name='JDGoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(max_length=256, verbose_name='评论用户名')),
                ('star', models.CharField(max_length=10, verbose_name='评分')),
                ('content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('date', models.CharField(max_length=20, verbose_name='评论时间')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='爬取时间')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to='spider.JDGoods')),
            ],
        ),
    ]
