# Generated by Django 2.2.6 on 2019-10-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jdgoods',
            old_name='commit_num',
            new_name='comment_num',
        ),
        migrations.AddField(
            model_name='jdgoods',
            name='cv',
            field=models.CharField(default=22, max_length=128, verbose_name='评论编号'),
            preserve_default=False,
        ),
    ]
