# Generated by Django 2.2.6 on 2019-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_auto_20191023_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoodscomment',
            name='user_pr',
            field=models.CharField(default=1, max_length=256, verbose_name='用户省份'),
            preserve_default=False,
        ),
    ]
