# Generated by Django 2.2.6 on 2019-10-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_jdgoodscomment_user_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdgoodscomment',
            name='user_pr',
        ),
    ]
