# Generated by Django 2.2.6 on 2019-10-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_remove_jdgoodscomment_user_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='type',
            field=models.IntegerField(choices=[(1, '中国联通'), (2, '中国移动'), (3, '中国电信'), (4, '未知')], default=4, verbose_name='类别'),
        ),
    ]
