# Generated by Django 2.2.6 on 2019-10-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_jdgoods_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='page',
            field=models.IntegerField(default=1, max_length=128, verbose_name='页数'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jdgoods',
            name='type',
            field=models.IntegerField(choices=[(1, '中国移动'), (2, '中国联通'), (3, '中国电信'), (4, '未知')], default=4, verbose_name='类别'),
        ),
    ]
