# Generated by Django 2.2.6 on 2019-10-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0006_auto_20191024_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='flag',
            field=models.IntegerField(choices=[(0, '未爬取'), (1, '已爬取')], default=0, verbose_name='该商品评论是否爬取'),
        ),
    ]
