# Generated by Django 2.2.6 on 2019-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0007_jdgoods_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoodscomment',
            name='sentiment',
            field=models.IntegerField(choices=[(1, '满意'), (2, '一般'), (3, '不满意'), (4, '未知')], default=4, verbose_name='用户情感'),
        ),
    ]
