# Generated by Django 2.2.6 on 2019-10-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0008_jdgoodscomment_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='good_type',
            field=models.IntegerField(choices=[(1, '电话卡'), (2, '宽带'), (3, '手机'), (4, '路由器'), (5, '其它')], default=5, verbose_name='商品类别'),
        ),
    ]
