# Generated by Django 2.2.6 on 2019-10-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0009_jdgoods_good_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='num_flag',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='该商品评论数量是否重复'),
        ),
        migrations.AlterField(
            model_name='jdgoods',
            name='page',
            field=models.IntegerField(verbose_name='页数'),
        ),
    ]
