# Generated by Django 2.2.6 on 2019-11-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0012_spiderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderconfig',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
