# Generated by Django 2.2.6 on 2019-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0013_spiderconfig_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdgoods',
            name='is_flagship',
            field=models.IntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否为官方旗舰店'),
        ),
    ]
